# Generated by Django 5.0.7 on 2024-07-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='AIImage',
        ),
    ]
