# Generated by Django 5.0.7 on 2024-07-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_alter_aiimage_chat_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='public/examples'),
        ),
    ]
